### ISSUE TITLE
2.2.1 Doesn't connect, 2.0 hangs with Win 10, Ceph NBD 18.5.2.0

### ISSUE THREAD

**Issue by nroach44** [SvenGDK/PSX-XMB-Manager#1]
I'm trying to connect to a PSX on the same local network. When using `nbd-client` (on Linux) I can successfully read out the drive, however PSX-XMB-Manager 2.2.1 gives a generic error when trying to connect:

````
Could not connect to the PSX.
Please check your IP address.
````

When using 2.0, it connects OK but ether reports that the drive isn't connected, or hangs when trying to do things with it.

I've tried with the firewall turned off to no avail.

![image](https://github.com/SvenGDK/PSX-XMB-Manager/assets/518487/8be9b782-ba59-4e27-9da0-09d7f4a4def5)

**Comment by Franzkill** [comment]
Having the same issue not being able to connect. Also have issues with installing the Dokan driver :(

**Comment by SvenGDK** [comment]
@nroach44 @Franzkill 

Please try with a lower NBD driver (0.5 or lower).
Seems like they tend to change the connection parameters and behaviour or their driver with almost every new release...

**Comment by Franzkill** [comment]
Do you know where I can download the lower versions? Can only seem to see the latest one on the website

**Comment by nroach44** [comment]
Yup, can confirm that all three releases (reef, quincy etc.) on the ceph site all end up giving you 0.7.0.

**Comment by nroach44** [comment]
This installer results in the version reporting `0.5.0-15-g7d87bdb`:

[ceph_quincy_beta.msi](https://web.archive.org/web/20230702020420/https://cloudbase.it/downloads/ceph_quincy_beta.msi)

I'll be able to test it later today or tomorrow to see if it actually works though.

**Comment by nroach44** [comment]
No luck:
![image](https://github.com/SvenGDK/PSX-XMB-Manager/assets/518487/fba06d30-9bd1-42f0-89b9-b4e06409b4d0)

**Comment by SvenGDK** [comment]
> No luck: ![image](https://private-user-images.githubusercontent.com/518487/293720448-fba06d30-9bd1-42f0-89b9-b4e06409b4d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTUxNjUsIm5iZiI6MTcwNDIxNDg2NSwicGF0aCI6Ii81MTg0ODcvMjkzNzIwNDQ4LWZiYTA2ZDMwLTliZDEtNDJmMC04OWI5LWI0ZTA2NDA5YjRkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNzAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzgzYmQ5Y2NiZmU4MjJjMTQxOGVjMzc5M2M1ZjBkYzNhYTFjZThmNzk1YzZiNmRiNDk4NTJhMTM5NDBjZTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KGfEzxltdW99ZHFU5dWGJds-bJNOXiHzjOkcNG6R0Yw)

Very strange. Which OPL build are actually you using ?
I recommend you to try with my build that has been created especially for the PSX:
https://github.com/SvenGDK/Open-PS2-Loader

**Comment by Franzkill** [comment]
Same issue still. And yes using that specific OPL build. I can post a screenshot of my network settings on OPL if that helps?

**Comment by Franzkill** [comment]
Also I'm connected to the same network wirelessly using my Surface Pro 8. Could that be an issue also?

**Comment by SvenGDK** [comment]
Didn't test with Wifi yet, only on LAN.
Here's the guide I created before v2. The video will start at the network settings, make sure they are correct :
https://youtu.be/FuPfzTY-Tps?t=65

**Comment by Franzkill** [comment]
Already did it via the guide with those settings. Ill try switching to LAN/wired. Other frustrating thing is my desktops buggered up :(

**Comment by SvenGDK** [comment]
Use the recently posted drivers to resolve connection issues :
https://github.com/SvenGDK/PSX-XMB-Manager/releases/download/v2.2.1/NBD.0.5.0-15.+.Dokan.Driver.0x190.7z
