### ISSUE TITLE
PSX XMB MANAGER

### ISSUE THREAD

**Issue by RetroMod9898** [SvenGDK/PSX-XMB-Manager#2]
The Issue with the application is when I setup the process with required programs to run the psx manager I've typed in my psx ip address numbers on the application for some reason it's not registering then I went and use the oldest application and it connects with no problem I think the Issue needs to be resolved before releasing the source I'm sure couple of people have this common issue but it needs to be fixed and further testing before releasing the source it self!

**Comment by SvenGDK** [comment]
> The Issue with the application is when I setup the process with required programs to run the psx manager I've typed in my psx ip address numbers on the application for some reason it's not registering then I went and use the oldest application and it connects with no problem I think the Issue needs to be resolved before releasing the source I'm sure couple of people have this common issue but it needs to be fixed and further testing before releasing the source it self!

Latest NBD drivers are not supported yet and make this tool unsable (atm).
Use the recently posted drivers https://github.com/SvenGDK/PSX-XMB-Manager/releases/download/v2.2.1/NBD.0.5.0-15.+.Dokan.Driver.0x190.7z in case you have issues.
